name: Build and Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install fyne-cross
        run: |
          go install github.com/fyne-io/fyne-cross@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Cross-Compile for Windows
        run: fyne-cross windows -arch=amd64 --app-id com.keestucker.husk

      - name: Release Please
        id: release_please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows Build
        if: ${{ steps.release_please.outputs.release_created == 'true' }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release_please.outputs.upload_url }}
          asset_path: ./fyne-cross/bin/windows-amd64/husk.exe
          asset_name: husk.exe
          asset_content_type: application/octet-stream
