name: Build and Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Release Please
        id: release_please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install fyne-cross
        if: ${{ steps.release_please.outputs.release_created == 'true' }}
        run: |
          go install github.com/fyne-io/fyne-cross@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Cross-Compile for Windows
        if: ${{ steps.release_please.outputs.release_created == 'true' }}
        run: fyne-cross windows --app-id com.keestucker.husk --icon ./Icon.png

      - name: Cross-Compile for Linux
        if: ${{ steps.release_please.outputs.release_created == 'true' }}
        run: fyne-cross linux --app-id com.keestucker.husk --icon ./Icon.png

      - name: Upload Windows amd64 Build
        if: ${{ steps.release_please.outputs.release_created == 'true' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_please.outputs.upload_url }}
          asset_path: ./fyne-cross/bin/windows-amd64/husk.exe
          asset_name: husk-windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload Linux amd64 Build
        if: ${{ steps.release_please.outputs.release_created == 'true' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_please.outputs.upload_url }}
          asset_path: ./fyne-cross/bin/linux-amd64/husk
          asset_name: husk-linux-amd64
          asset_content_type: application/octet-stream