name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Set up Fyne Dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev

      - name: Go Mod Tidy
        run: go mod tidy

      - name: Build Application
        run: go build -v -o husk

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: husk
          path: husk
