name: Release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: husk
          path: .

      - name: "Release Please"
        id: release_please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Release Information
        id: extract_release_info
        if: ${{ steps.release_please.outputs.releases_created == 'true' }}
        run: |
          echo '${{ steps.release_please.outputs.releases_created }}' > releases_created.json
          TAG_NAME=$(jq -r '.[0].tagName' releases_created.json)
          UPLOAD_URL=$(jq -r '.[0].uploadUrl' releases_created.json)
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "UPLOAD_URL=$UPLOAD_URL" >> $GITHUB_ENV

      - name: Upload Release Asset
        if: ${{ steps.release_please.outputs.releases_created == 'true' }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./husk
          asset_name: husk
          asset_content_type: application/octet-stream
